if: commit_message != "Deploy anchal-physics/bodyMeasurements to github.com/anchal-physics/bodyMeasurements.git:master"
language: python
python:
- 3.6.4
cache: pip
install:
- pip install -r requirements.txt
script:
- python bodyMeasurements.py --type $type --project_id $project_id --private_key_id $private_key_id --private_key $private_key --client_email $client_email --client_id $client_id --auth_uri $auth_uri --token_uri $token_uri --auth_provider_x509_cert_url $auth_provider_x509_cert_url --client_x509_cert_url $client_x509_cert_url
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  target_branch: master
#before_install:
#- openssl aes-256-cbc -K $encrypted_a19a2544770a_key -iv $encrypted_a19a2544770a_iv
#  -in BodyMeasurements-2685fd4ece78.json.enc -out BodyMeasurements-2685fd4ece78.json
#  -d
