language: python
python:
- 3.6.4
cache: pip
install:
- pip install -r requirements.txt
script:
- python bodyMeasurements.py
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_65bde58e4bc5_key -iv $encrypted_65bde58e4bc5_iv -in bodymeasurements-d291f81a84a8.json.enc -out bodymeasurements-d291f81a84a8.json -d
