#if: commit_message != "Deploy anchal-physics/bodyMeasurements to github.com/anchal-physics/bodyMeasurements.git:master"
language: python
python:
- 3.6.4
cache: pip
install:
- pip install -r requirements.txt
script:
- python bodyMeasurements.py
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  keep_history: true
  commit_message: "[skip travis-ci] Automatic travis deployment"
  on:
    branch: master
  target_branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_485e24aa73cb_key -iv $encrypted_485e24aa73cb_iv
  -in BodyMeasurements-74d397ae9641.json.enc -out BodyMeasurements-74d397ae9641.json
  -d
