name: Analyze Data
on:
  schedule:
    - cron: '0 19 * * *'
  push:
    branches:
      - master
jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Service Account Credentials
        run: ./decryptJSON.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python bodyMeasurements.py
      - name: 'Upload body measurements plot'
        uses: actions/upload-artifact@v4
        with:
          name: Body Measurements Time Series
          path: ./public/BodyMeasurementsTimeSeries.pdf
          retention-days: 2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
