name: Analyze Data
on:
  schedule:
    - cron: '30 0 * * *'
  push:
    branches:
      - master
jobs:
  Analyze:
    runs-on: ubuntu-latest
    environment: AnalyzeData
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: openssl enc -nosalt -aes-256-cbc -d -base64 -K $KEY -iv $INIT_VECT -in bodymeasurements-d291f81a84a8.json.enc -out bodymeasurements-d291f81a84a8.json -d
      - run: python bodyMeasurements.py
